#Tomcat-Nginx-

    depends_on:
            - tomcat01
            - tomcat02
            - tomcat03

    tomcat01:
        image: tomcat
        container_name: cyk_tomcat1
        volumes:
            - ./tomcat01:/usr/local/tomcat/webapps/ROOT # 挂载web目录

    tomcat02:
        image: tomcat
        container_name: cyk_tomcat2
        volumes:
            - ./tomcat02:/usr/local/tomcat/webapps/ROOT

    tomcat03:
        image: tomcat
        container_name: cyk_tomcat3
        volumes:
            - ./tomcat03:/usr/local/tomcat/webapps/ROOT
            
#    LNMP
ervices:
 nginx:
    image: mynginx_image                #指定镜像名
    container_name: mynginx             #指定容器名
    build:
      context: .
      dockerfile: dockerfile_nginx      #指定dockerfile文件
    ports:
      - "80:2020"                       #修改端口映射
    volumes:
      - ./web:/web/html                 #挂载容器卷，本地/容器内修改文件后，另一方都会同步更新；
      - ./default.conf:/etc/nginx/conf.d/default.conf     #挂载配置文件

 php:
    image: myphp_image
    container_name: myphp
    build:
      context: .
      dockerfile: dockerfile_php
    environment:
      MYSQL_PASSWORD: 123            #设置好环境变量，在php代码中使用变量名直接引用
    volumes:
    - ./web:/web/php                  #挂载工作目录到本机web目录

 mysql:
   image: mysql_image
   container_name: mysql
   build:
      context: .
      dockerfile: dockerfile_mysql
   ports:
     - "3306:3306"
   volumes:
     - ./mysql_data:/var/lib/mysql       #挂载容器卷，实现数据同步，防止数据丢失

 phpmyadmin:
   image: myphpadmin_image
   container_name: myphpmyadmin
   build:
      context: .
      dockerfile: dockerfile_phpmyadmin
   ports:
     - "8080:80"
   environment:
       PMA_HOST: mysql
                             
